name: Curve
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  charts_flutter: ^0.12.0
  cloud_firestore: ^4.16.1
  connectivity_plus: ^6.0.2
  dio: ^5.4.2+1
  firebase_auth: ^4.19.1
  flappy_search_bar_ns: ^2.0.2
  flutter:
    sdk: flutter
  flutter_custom_clippers: ^2.1.0
  flutter_signin_button: ^2.0.0
  flutter_spinkit: ^5.2.1
  fluttertoast: ^8.2.4
  http: ^1.2.1
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  syncfusion_flutter_charts: ^21.2.4
  url_launcher: ^6.2.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - external_sources/
